// Generated by CoffeeScript 1.9.3
(function() {
  var log,
    slice = [].slice;

  log = function() {
    var args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return console.log.apply(console, ['TCLAS:'].concat(slice.call(args)));
  };

  module.exports = function(options, cssObj) {
    var classes, css, cssStack, getClasses, ref;
    if (arguments.length < 2) {
      cssObj = options;
      options = {};
    }
    classes = {};
    cssStack = [(ref = options.namespace) != null ? ref : 'global'];
    css = '';
    (getClasses = function(cssObj) {
      var className, klass, parentClass, results, val;
      results = [];
      for (klass in cssObj) {
        val = cssObj[klass];
        parentClass = cssStack.join('-');
        className = parentClass + '-' + klass;
        if (klass === '_') {
          if (typeof val !== 'string') {
            throw new Error('TeaClass Error: _ property must be a string: ' + parentClass);
          }
          results.push(css += "\n." + parentClass + "{\n" + val + "\n}");
        } else if (typeof val === 'string') {
          results.push(css += "\n." + className + "{\n" + val + "\n}");
        } else {
          if (klass in classes) {
            throw new Error('TeaClass Error: Duplicate class name: ' + className);
          }
          classes[klass] = className;
          if (typeof val === 'object') {
            cssStack.push(klass);
            getClasses(val);
            results.push(cssStack.pop());
          } else {
            throw new Error('TeaClass Error: property must be _ or an object: ' + className);
          }
        }
      }
      return results;
    })(cssObj);
    (document.head.appendChild(document.createElement('style'))).textContent = css + '\n';
    return function(klass, ele) {
      if (ele == null) {
        ele = document.body;
      }
      return ele.querySelector('.' + classes[klass]);
    };
  };

}).call(this);
